document.addEventListener('DOMContentLoaded', () => {
    const estilos = [
        "contenedores/botones.css",
        "contenedores/contenedores.css",
        "historial/historial.css",
        "carrusel/carrusel.css",
        "contenedores/calcpnt.css",
        "modos/blue.css",
        "modos/green.css",
        "modos/negro.css",
        "modos/blanco.css",
        "modos/pastel.css",
        "modos/neon.css",
        "modos/cyber.css",
        "modos/aurora.css"
    ];

    const scripts = [
        "calculos/conversiones.js",
        "calculos/Basica.js",
        "calculos/divisas.js",
        "calculos/macros.js",
        "calculos/fechas.js",
        "calculos/interes.js",
        "calculos/pokemon.js",
        "calculos/IMC.js",
        "calculos/clima.js",
        "calculos/programador.js",
        "calculos/deportiva.js",
        "carrusel/carrusel.js",
        "historial/historial.js",
        "modos/estilos.js",
        "acciones/acciones.js",
        "acciones/funcionalidadTeclado.js",
        "acciones/resoluciones.js"
    ];

    estilos.forEach(href => {
        const link = document.createElement("link");
        link.rel = "stylesheet";
        link.href = href;
        document.head.appendChild(link);
    });

    cargarScriptsEnOrden(scripts);
    cargarDivisas();
});

function cargarScriptsEnOrden(scripts) {
    cargarSiguiente(scripts, 0);
}

function cargarSiguiente(scripts, index) {
    if (index >= scripts.length) return;

    const script = document.createElement("script");
    script.src = scripts[index];

    script.onload = () => {
        cargarSiguiente(scripts, index + 1);
    };

    script.onerror = () => {
        console.error("Error cargando:", scripts[index]);
    };

    document.body.appendChild(script);
}
function cargarDivisas() {
    const divisas = [
        "USD — Dólar estadounidense",
        "AED — Dirham de Emiratos Árabes Unidos",
        "AFN — Afgani afgano",
        "ALL — Lek albanés",
        "AMD — Dram armenio",
        "ANG — Florín de las Antillas Neerlandesas",
        "AOA — Kwanza angoleño",
        "ARS — Peso argentino",
        "AUD — Dólar australiano",
        "AWG — Florín arubeño",
        "AZN — Manat azerbaiyano",
        "BAM — Marco convertible bosnio",
        "BBD — Dólar barbadense",
        "BDT — Taka bangladesí",
        "BGN — Lev búlgaro",
        "BHD — Dinar bareiní",
        "BIF — Franco burundés",
        "BMD — Dólar bermudeño",
        "BND — Dólar de Brunéi",
        "BOB — Boliviano",
        "BRL — Real brasileño",
        "BSD — Dólar bahameño",
        "BTN — Ngultrum butanés",
        "BWP — Pula botsuano",
        "BYN — Rublo bielorruso",
        "BZD — Dólar beliceño",
        "CAD — Dólar canadiense",
        "CDF — Franco congoleño",
        "CHF — Franco suizo",
        "CLF — Unidad de Fomento (Chile)",
        "CLP — Peso chileno",
        "CNH — Yuan chino (offshore)",
        "CNY — Yuan chino (Renminbi)",
        "COP — Peso colombiano",
        "CRC — Colón costarricense",
        "CUP — Peso cubano",
        "CVE — Escudo caboverdiano",
        "CZK — Corona checa",
        "DJF — Franco yibutiano",
        "DKK — Corona danesa",
        "DOP — Peso dominicano",
        "DZD — Dinar argelino",
        "EGP — Libra egipcia",
        "ERN — Nakfa eritreo",
        "ETB — Birr etíope",
        "EUR — Euro",
        "FJD — Dólar fiyiano",
        "FKP — Libra malvinense",
        "FOK — Corona feroesa",
        "GBP — Libra esterlina",
        "GEL — Lari georgiano",
        "GGP — Libra de Guernsey",
        "GHS — Cedi ghanés",
        "GIP — Libra de Gibraltar",
        "GMD — Dalasi gambiano",
        "GNF — Franco guineano",
        "GTQ — Quetzal guatemalteco",
        "GYD — Dólar guyanés",
        "HKD — Dólar de Hong Kong",
        "HNL — Lempira hondureña",
        "HRK — Kuna croata",
        "HTG — Gourde haitiano",
        "HUF — Forinto húngaro",
        "IDR — Rupia indonesia",
        "ILS — Nuevo séquel israelí",
        "IMP — Libra de la Isla de Man",
        "INR — Rupia india",
        "IQD — Dinar iraquí",
        "IRR — Rial iraní",
        "ISK — Corona islandesa",
        "JEP — Libra de Jersey",
        "JMD — Dólar jamaiquino",
        "JOD — Dinar jordano",
        "JPY — Yen japonés",
        "KES — Chelín keniano",
        "KGS — Som kirguís",
        "KHR — Riel camboyano",
        "KID — Dólar de Kiribati",
        "KMF — Franco comorense",
        "KRW — Won surcoreano",
        "KWD — Dinar kuwaití",
        "KYD — Dólar de las Islas Caimán",
        "KZT — Tenge kazajo",
        "LAK — Kip laosiano",
        "LBP — Libra libanesa",
        "LKR — Rupia de Sri Lanka",
        "LRD — Dólar liberiano",
        "LSL — Loti lesotense",
        "LYD — Dinar libio",
        "MAD — Dirham marroquí",
        "MDL — Leu moldavo",
        "MGA — Ariary malgache",
        "MKD — Denar macedonio",
        "MMK — Kyat birmano",
        "MNT — Tugrik mongol",
        "MOP — Pataca de Macao",
        "MRU — Uguiya mauritana",
        "MUR — Rupia mauriciana",
        "MVR — Rufiyaa maldiva",
        "MWK — Kwacha malauí",
        "MXN — Peso mexicano",
        "MYR — Ringgit malasio",
        "MZN — Metical mozambiqueño",
        "NAD — Dólar namibio",
        "NGN — Naira nigeriana",
        "NIO — Córdoba nicaragüense",
        "NOK — Corona noruega",
        "NPR — Rupia nepalí",
        "NZD — Dólar neozelandés",
        "OMR — Rial omaní",
        "PAB — Balboa panameño",
        "PEN — Sol peruano",
        "PGK — Kina papuana",
        "PHP — Peso filipino",
        "PKR — Rupia pakistaní",
        "PLN — Zloty polaco",
        "PYG — Guaraní paraguayo",
        "QAR — Rial catarí",
        "RON — Leu rumano",
        "RSD — Dinar serbio",
        "RUB — Rublo ruso",
        "RWF — Franco ruandés",
        "SAR — Riyal saudí",
        "SBD — Dólar de las Islas Salomón",
        "SCR — Rupia seychellense",
        "SDG — Libra sudanesa",
        "SEK — Corona sueca",
        "SGD — Dólar de Singapur",
        "SHP — Libra de Santa Elena",
        "SLE — Leone (nuevo) de Sierra Leona",
        "SLL — Leone (antiguo) de Sierra Leona",
        "SOS — Chelín somalí",
        "SRD — Dólar surinamés",
        "SSP — Libra sursudanesa",
        "STN — Dobra de Santo Tomé y Príncipe",
        "SYP — Libra siria",
        "SZL — Lilangeni suazi",
        "THB — Baht tailandés",
        "TJS — Somoni tayiko",
        "TMT — Manat turcomano",
        "TND — Dinar tunecino",
        "TOP — Paʻanga tongano",
        "TRY — Lira turca",
        "TTD — Dólar de Trinidad y Tobago",
        "TVD — Dólar de Tuvalu",
        "TWD — Dólar taiwanés",
        "TZS — Chelín tanzano",
        "UAH — Grivna ucraniana",
        "UGX — Chelín ugandés",
        "UYU — Peso uruguayo",
        "UZS — Som uzbeko",
        "VES — Bolívar venezolano",
        "VND — Dong vietnamita",
        "VUV — Vatu vanuatuense",
        "WST — Tala samoano",
        "XAF — Franco CFA de África Central",
        "XCD — Dólar del Caribe Oriental",
        "XCG — Florín del Caribe Neerlandés",
        "XDR — Derechos Especiales de Giro (FMI)",
        "XOF — Franco CFA de África Occidental",
        "XPF — Franco CFP",
        "YER — Rial yemení",
        "ZAR — Rand sudafricano",
        "ZMW — Kwacha zambiano",
        "ZWG — Dólar zimbabuense (Gold)",
        "ZWL — Dólar zimbabuense"
    ];

    document.getElementById("divisas").innerHTML = divisas.map(d => `<p>${d}</p>`).join('');
}