name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        env:
          API_KEY_CLIMA: ${{ secrets.API_KEY_CLIMA }}
          API_KEY_DIVISAS: ${{ secrets.API_KEY_DIVISAS }}

      - name: Run tests or app
        run: node app.js
        env:
          API_KEY_CLIMA: ${{ secrets.API_KEY_CLIMA }}
          API_KEY_DIVISAS: ${{ secrets.API_KEY_DIVISAS }}